name: Astronomer-CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Astronomer.io
      uses: elgohr/Publish-Docker-Github-Action@2.6
      with:
        name: development/airflow:ci-${{ github.sha }}
        username: _
        password: 49bdc9c63ccf20c6be9c33390cc1b219
        registry: registry.gcp0001.us-east4.astronomer.io
